buffer=[];
query = sprintf(['SELECT i_id,i_orderid,i_requestid,'...
          'i_clordid,i_msgnum,i_tradeid,i_contrabroker,'...
          'i_timestamp,i_tag,t_time,d_price,d_value '...
          'FROM dbaccounts.omstrades '...
          'WHERE s_source=''RT'' '...
          'AND s_tradedate>=''2016-07-01'' '...
          'AND s_account=''MASTERKPTL'' '...
          'AND s_strategy=''Channel'' '...
          'AND s_oms = ''XP_FIXBMF'' ;']);
h = mysql( 'open', 'BDKPTL03','traders', 'kapitalo' );
[ buffer(:,1),buffer(:,2),buffer(:,3),...
  buffer(:,4),buffer(:,5),buffer(:,6),...
  buffer(:,7),buffer(:,8),buffer(:,9),...
  buffer(:,10),buffer(:,11),buffer(:,12) ] = mysql(query);
mysql('close') 