
tic
str_query = 's_source,p_tradedate,p_exchange,p_symbol,s_market,s_contract,s_contractType,s_m2mType,s_lastM2mType,s_symbolVoice,s_channels,t_strikedate,t_lasttrade,t_liquidation,t_deliveryDate,t_time,d_open,d_max,d_min,d_close,d_closeQty,d_lastClose,d_last,d_avg,d_bestBid,d_bidQty,d_bestAsk,d_askQty,d_trades,d_contracts,d_openInterest,d_volumeBRL,d_volumeUSD,d_pointvalue,d_m2m,d_lastM2m,d_m2mReturn,d_m2mValue,d_dM2m,d_dM2mValue,d_strikeprice,d_exercBRL,d_exercUSD,d_exercTrades,d_exercContracts,d_delta,d_yieldDays,d_totalDays,d_busDays,d_margin,d_marginMM,d_futSeq,d_lowerLimit,d_upperLimit';

currdate = datenum(2016,01,01);
t=1;
query = sprintf(['SELECT %s FROM dbmarketdata.daily '...
                  'WHERE p_exchange=''XBMF'''...
                  'AND p_tradedate>=''%s'' '...
                  'ORDER BY p_tradedate;'],...
                  str_query,datestr(currdate,'yyyy-mm-dd'));
h = mysql( 'open', 'localhost','traders', 'kapitalo' );
[this.quotes.daily(t).s_source,this.quotes.daily(t).s_tradedate,this.quotes.daily(t).s_exchange,...
  this.quotes.daily(t).s_symbol,this.quotes.daily(t).s_market,this.quotes.daily(t).s_contract,...
  this.quotes.daily(t).s_contractType,this.quotes.daily(t).s_m2mType,this.quotes.daily(t).s_lastM2mType,...
  this.quotes.daily(t).s_symbolVoice,this.quotes.daily(t).s_channels,this.quotes.daily(t).t_strikedate,...
  this.quotes.daily(t).t_lasttrade,this.quotes.daily(t).t_liquidation,this.quotes.daily(t).t_deliveryDate,...
  this.quotes.daily(t).t_time,this.quotes.daily(t).d_open,this.quotes.daily(t).d_max,this.quotes.daily(t).d_min,...
  this.quotes.daily(t).d_close,this.quotes.daily(t).d_closeQty,this.quotes.daily(t).d_lastClose,...
  this.quotes.daily(t).d_last,this.quotes.daily(t).d_avg,this.quotes.daily(t).d_bestBid,this.quotes.daily(t).d_bidQty,...
  this.quotes.daily(t).d_bestAsk,this.quotes.daily(t).d_askQty,this.quotes.daily(t).d_trades,...
  this.quotes.daily(t).d_contracts,this.quotes.daily(t).d_openInterest,this.quotes.daily(t).d_volumeBRL,...
  this.quotes.daily(t).d_volumeUSD,this.quotes.daily(t).d_pointvalue,this.quotes.daily(t).d_m2m,...
  this.quotes.daily(t).d_lastM2m,this.quotes.daily(t).d_m2mReturn,this.quotes.daily(t).d_m2mValue,...
  this.quotes.daily(t).d_dM2m,this.quotes.daily(t).d_dM2mValue,this.quotes.daily(t).d_strikeprice,...
  this.quotes.daily(t).d_exercBRL,this.quotes.daily(t).d_exercUSD,this.quotes.daily(t).d_exercTrades,...
  this.quotes.daily(t).d_exercContracts,this.quotes.daily(t).d_delta,this.quotes.daily(t).d_yieldDays,...
  this.quotes.daily(t).d_totalDays,this.quotes.daily(t).d_busDays,this.quotes.daily(t).d_margin,...
  this.quotes.daily(t).d_marginMM,this.quotes.daily(t).d_futSeq,this.quotes.daily(t).d_lowerLimit,...
  this.quotes.daily(t).d_upperLimit] = mysql(query);
mysql('close')
toc
%}

dolidx = strcmp(this.quotes.daily.s_market,'DOL');
indidx = strcmp(this.quotes.daily.s_market,'IND');
futidx = strcmp(this.quotes.daily.s_contractType,'FUT');
firstidx = this.quotes.daily.d_futSeq == 1;
dolfutidx = dolidx & futidx & firstidx;
indfutidx = indidx & futidx & firstidx;
dolfutpx = this.quotes.daily.d_m2m(dolfutidx);
indfutpx = this.quotes.daily.d_m2m(indfutidx);
dolfutdays = this.quotes.daily.s_tradedate(dolfutidx);
frpidx = strcmp(this.quotes.daily.s_contract,'FRP0');
frppx = this.quotes.daily.d_m2m(frpidx);
ptaxpx = (dolfutpx-frppx);
dolr = ptaxpx./ptaxpx(1);
indr = indfutpx./indfutpx(1);

figure
stairs(dolfutdays,dolr)
hold on
stairs(dolfutdays,indr)
stairs(dolfutdays,indr.*(1./dolr))
datetick('x')