te = tic;
dstart = datenum(2016,01,04);
dend = datenum(2016,09,01);

h = mysql( 'open', 'localhost','traders', 'kapitalo' );
query = sprintf(['SELECT COLUMN_NAME ',...
                  'FROM INFORMATION_SCHEMA.COLUMNS ',...
                  'WHERE TABLE_SCHEMA = ''%s'' ',...
                  'AND TABLE_NAME = ''%s'';'],...
                  'dbmarket',...
                  'mdquotes');
[ fields ] = mysql(query);
mysql('close') 
cols_count=0;
%create dictionary
for f=1:length(fields)
  column = strsplit(cell2mat(fields(f)),'_');
  if size(column,2)>1
    if ~strcmp(column{1},'s')
      cols_count = cols_count +1;
      cols.(column{2:end}) = cols_count;
      dictionary{cols_count} = fields{f};
      columns{cols_count} = column{2:end};
      columns_type{cols_count} = column{1};
    end
  end
end

quotes.symbol=cell(10000000,1);
quotes.data=zeros(10000000,13);
quotes.count = 0;
for t=round(dstart):round(dend)
  td = tic;
  
  h = mysql( 'open', 'localhost','traders', 'kapitalo' );
  query = sprintf(['select s_symbol,'...
                    'i_id,t_time,d_open,d_close,d_max,d_min,'...
                    'd_volume,d_buyvolume,d_sellvolume,'...
                    'd_bestbid,d_bidqty,d_bestask,d_askqty '...
                    'from dbmarket.mdquotes ',...
                    'where s_source=''RT'' ',...
                    'and s_tradedate = ''%s'' '...
                    'and s_marketdata = 4 '...
                    'and s_period = ''S15'' '...
                    'and s_symbol in '...
                    '(SELECT s_symbol FROM dbconfig.series '...
                    'where s_serie=''DOLFUT'' '...
                    'and s_name=''FULL'' '...
                    'group by s_symbol);'],...
                    datestr(t,'yyyy-mm-dd'));
  [ buffer.symbol,  buffer.id,      buffer.time,...
    buffer.open,    buffer.close,   buffer.max,buffer.min,...
    buffer.volume,  buffer.buyvolume,buffer.sellvolume,...
    buffer.bestbid, buffer.bidqty,buffer.bestask,buffer.askqty] = ...
    mysql(query);
  mysql('close') 
  if size(buffer.symbol,1)>0
  newidx = quotes.count+1:quotes.count+size(buffer.symbol,1);
  newidx = newidx';
  quotes.symbol(newidx) = buffer.symbol;
  quotes.data(newidx,cols.id) = buffer.id;
  quotes.data(newidx,cols.time) = buffer.time;
  quotes.data(newidx,cols.open) = buffer.open;
  quotes.data(newidx,cols.close) = buffer.close;
  quotes.data(newidx,cols.max) = buffer.max;
  quotes.data(newidx,cols.min) = buffer.min;
  quotes.data(newidx,cols.volume) = buffer.volume;
  quotes.data(newidx,cols.buyvolume) = buffer.buyvolume;
  quotes.data(newidx,cols.sellvolume) = buffer.sellvolume;
  quotes.data(newidx,cols.bestbid) = buffer.bestbid;
  quotes.data(newidx,cols.bidqty) = buffer.bidqty;
  quotes.data(newidx,cols.bestask) = buffer.bestask;
  quotes.data(newidx,cols.askqty) = buffer.askqty;
  quotes.count = quotes.count + size(buffer.symbol,1);
  quotes.count
  end
  tday = toc(td);
  fprintf('%s , %f\n',datestr(t,'yyyy-mm-dd'),tday)
end

%{
quotes.id=[];
quotes.time=[];
quotes.open=[];
quotes.close=[];
quotes.max=[];
quotes.min=[];
quotes.volume=[];
quotes.buyvolume=[];
quotes.sellvolume=[];
quotes.bestbid=[];
quotes.bidqty=[];
quotes.bestask=[];
quotes.askqty=[];
mdquotes(1:round(dend)) = quotes;
for t=round(dstart):round(dend)
  tic
  h = mysql( 'open', 'localhost','traders', 'kapitalo' );
  query = sprintf(['select s_symbol,'...
                    'i_id,t_time,d_open,d_close,d_max,d_min,'...
                    'd_volume,d_buyvolume,d_sellvolume,'...
                    'd_bestbid,d_bidqty,d_bestask,d_askqty '...
                    'from dbmarket.mdquotes ',...
                    'where s_source=''RT'' ',...
                    'and s_tradedate = ''%s'' '...
                    'and s_marketdata = 4 '...
                    'and s_period = ''S15'' '...
                    'and s_symbol in '...
                    '(SELECT s_symbol FROM dbconfig.series '...
                    'where s_serie=''DOLFUT'' '...
                    'and s_name=''FULL'' '...
                    'group by s_symbol);'],...
                    datestr(t,'yyyy-mm-dd'));
  [ quotes.symbol,  quotes.id,      quotes.time,...
    quotes.open,    quotes.close,   quotes.max,quotes.min,...
    quotes.volume,  quotes.buyvolume,quotes.sellvolume,...
    quotes.bestbid, quotes.bidqty,quotes.bestask,quotes.askqty] = ...
    mysql(query);
  mysql('close') 
  %mdquotes(t) = quotes;
  toc
end
%}

toc(te)